In [ ]:
#%pip install tensorflow

  Using cached setuptools-80.9.0-py3-none-any.whl.metadata (6.6 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 645.0/645.0 MB 47.7 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.0/6.0 MB 129.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 198.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.0/16.0 MB 209.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 188.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 198.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 192.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 60.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.5/24.5 MB 183.9 MB/s eta 0:00:00
Using cached setuptools-80.9.0-py3-none-any.whl (1.2 MB)
  Attempting uninstall: numpy━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10/34 [protobuf]s]-data-server]
    Found existing installation: numpy 2.3.1━━━━━━━━━━━━━━━━━━ 10/3

In [2]:
import tensorflow as tf
print(f"TensorFlow version: {tf.__version__}")

2025-06-26 00:35:55.517269: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-06-26 00:35:55.522006: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-06-26 00:35:55.532764: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1750898155.548699    4581 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1750898155.554311    4581 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1750898155.569773    4581 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linkin

TensorFlow version: 2.19.0


In [3]:
# Scalar (0D tensor)
scalar = tf.constant(42)

# Vector (1D tensor)
vector = tf.constant([1, 2, 3, 4])

# Matrix (2D tensor)
matrix = tf.constant([[1, 2], [3, 4], [5, 6]])

# 3D tensor
tensor_3d = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

2025-06-26 00:36:16.965869: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


In [4]:
# print("Scalar:", scalar)
# print("Vector:", vector)
# print("Matrix:\n", matrix)
print("3D Tensor:\n", tensor_3d)

3D Tensor:
 tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


In [5]:
# Creating tensors with specific data types
float_tensor = tf.constant([1.5, 2.5, 3.5], dtype=tf.float32)
int_tensor = tf.constant([1, 2, 3], dtype=tf.int32)

# Creating tensors with specific shapes
zeros = tf.zeros([3, 4])  # 3x4 tensor of zeros
ones = tf.ones([2, 3, 4])  # 2x3x4 tensor of ones
random = tf.random.normal([3, 3])  # 3x3 tensor of random values from a normal distribution

# Creating tensors from Python lists or NumPy arrays
import numpy as np
numpy_array = np.array([[1, 2], [3, 4]])
tensor_from_numpy = tf.constant(numpy_array)

print("Float Tensor:", float_tensor)
print("Int Tensor:", int_tensor)
print("Zeros:\n", zeros)
print("Ones:\n", ones)
print("Random:\n", random)
print("Tensor from NumPy:\n", tensor_from_numpy)

Float Tensor: tf.Tensor([1.5 2.5 3.5], shape=(3,), dtype=float32)
Int Tensor: tf.Tensor([1 2 3], shape=(3,), dtype=int32)
Zeros:
 tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(3, 4), dtype=float32)
Ones:
 tf.Tensor(
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]], shape=(2, 3, 4), dtype=float32)
Random:
 tf.Tensor(
[[ 0.7497312   2.0890765  -1.0730118 ]
 [ 0.33563375  1.240643    1.4998899 ]
 [ 1.9525177   0.684004    0.6682405 ]], shape=(3, 3), dtype=float32)
Tensor from NumPy:
 tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int64)


Operaciones con tensores

In [6]:
# Element-wise operations
a = tf.constant([2, 3])
b = tf.constant([4, 5])
result = a + b
print(f"Addition: {result}")

# Matrix multiplication
matrix_a = tf.constant([[1, 2], [3, 4]])
matrix_b = tf.constant([[5, 6], [7, 8]])
result = tf.matmul(matrix_a, matrix_b)
print(f"Matrix Multiplication:\\n{result}")

# Slicing tensors
tensor = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
slice = tensor[0:2, 1:3]
print(f"Sliced Tensor:\\n{slice}")

Addition: [6 8]
Matrix Multiplication:\n[[19 22]
 [43 50]]
Sliced Tensor:\n[[2 3]
 [5 6]]
