In [4]:
import pandas as ps
import numpy as np
import seaborn as sb
import matplotlib.pyplot as pl

from sklearn.metrics import classification_report
from sklearn import linear_model
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [5]:
datos = ps.read_csv("SeoulBikeData.csv")

In [6]:
datos

RentedBike  Hour  Temperature(C)  Humidity(%)  Wind(m/s)  \
0            254     0            -5.2           37        2.2   
1            204     1            -5.5           38        0.8   
2            173     2            -6.0           39        1.0   
3            107     3            -6.2           40        0.9   
4             78     4            -6.0           36        2.3   
...          ...   ...             ...          ...        ...   
8755        1003    19             4.2           34        2.6   
8756         764    20             3.4           37        2.3   
8757         694    21             2.6           39        0.3   
8758         712    22             2.1           41        1.0   
8759         584    23             1.9           43        1.3   

      Visibility(10m)  Dewpointtemperature(C)  SolarRadiation(MJ/m2)  \
0                2000                   -17.6                    0.0   
1                2000                   -17.6                    0.0   
2                2000                   -17.7                    0.0   
3                2000                   -17.6                    0.0   
4                2000                   -18.6                    0.0   
...               ...                     ...                    ...   
8755             1894                   -10.3                    0.0   
8756             2000                    -9.9                    0.0   
8757             1968                    -9.9                    0.0   
8758             1859                    -9.8                    0.0   
8759             1909                    -9.3                    0.0   

      Rainfall(mm)  Snowfall(cm)  
0              0.0           0.0  
1              0.0           0.0  
2              0.0           0.0  
3              0.0           0.0  
4              0.0           0.0  
...            ...           ...  
8755           0.0           0.0  
8756           0.0           0.0  
8757           0.0           0.0  
8758           0.0           0.0  
8759           0.0           0.0  

[8760 rows x 10 columns]

In [7]:
correlacion = datos.corr(method='pearson')
correlacion

RentedBike      Hour  Temperature(C)  Humidity(%)  \
RentedBike                1.000000  0.410257        0.538558    -0.199780   
Hour                      0.410257  1.000000        0.124114    -0.241644   
Temperature(C)            0.538558  0.124114        1.000000     0.159371   
Humidity(%)              -0.199780 -0.241644        0.159371     1.000000   
Wind(m/s)                 0.121108  0.285197       -0.036252    -0.336683   
Visibility(10m)           0.199280  0.098753        0.034794    -0.543090   
Dewpointtemperature(C)    0.379788  0.003054        0.912798     0.536894   
SolarRadiation(MJ/m2)     0.261837  0.145131        0.353505    -0.461919   
Rainfall(mm)             -0.123074  0.008715        0.050282     0.236397   
Snowfall(cm)             -0.141804 -0.021516       -0.218405     0.108183   

                        Wind(m/s)  Visibility(10m)  Dewpointtemperature(C)  \
RentedBike               0.121108         0.199280                0.379788   
Hour                     0.285197         0.098753                0.003054   
Temperature(C)          -0.036252         0.034794                0.912798   
Humidity(%)             -0.336683        -0.543090                0.536894   
Wind(m/s)                1.000000         0.171507               -0.176486   
Visibility(10m)          0.171507         1.000000               -0.176630   
Dewpointtemperature(C)  -0.176486        -0.176630                1.000000   
SolarRadiation(MJ/m2)    0.332274         0.149738                0.094381   
Rainfall(mm)            -0.019674        -0.167629                0.125597   
Snowfall(cm)            -0.003554        -0.121695               -0.150887   

                        SolarRadiation(MJ/m2)  Rainfall(mm)  Snowfall(cm)  
RentedBike                           0.261837     -0.123074     -0.141804  
Hour                                 0.145131      0.008715     -0.021516  
Temperature(C)                       0.353505      0.050282     -0.218405  
Humidity(%)                         -0.461919      0.236397      0.108183  
Wind(m/s)                            0.332274     -0.019674     -0.003554  
Visibility(10m)                      0.149738     -0.167629     -0.121695  
Dewpointtemperature(C)               0.094381      0.125597     -0.150887  
SolarRadiation(MJ/m2)                1.000000     -0.074290     -0.072301  
Rainfall(mm)                        -0.074290      1.000000      0.008500  
Snowfall(cm)                        -0.072301      0.008500      1.000000

In [22]:
X = datos[['Hour', 'Temperature(C)', 'Dewpointtemperature(C)']]
X_2 = datos[['Hour', 'Temperature(C)']]
X

Hour  Temperature(C)  Dewpointtemperature(C)
0        0            -5.2                   -17.6
1        1            -5.5                   -17.6
2        2            -6.0                   -17.7
3        3            -6.2                   -17.6
4        4            -6.0                   -18.6
...    ...             ...                     ...
8755    19             4.2                   -10.3
8756    20             3.4                    -9.9
8757    21             2.6                    -9.9
8758    22             2.1                    -9.8
8759    23             1.9                    -9.3

[8760 rows x 3 columns]

In [20]:
y = datos['RentedBike']
y

0        254
1        204
2        173
3        107
4         78
        ... 
8755    1003
8756     764
8757     694
8758     712
8759     584
Name: RentedBike, Length: 8760, dtype: int64

In [23]:
x_scaler = StandardScaler()
X_scaled = x_scaler.fit_transform(X_2)

In [39]:
y_scaler = StandardScaler()
y_scaled = y_scaler.fit_transform(y.values.reshape(-1, 1))


In [40]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.3, random_state=42)

In [41]:
X_train

array([[-1.08347268, -2.00792317],
       [ 1.2279357 , -1.56419106],
       [-0.50562058, -0.12415477],
       ...,
       [ 0.36115756,  1.39123226],
       [ 1.2279357 , -1.36325576],
       [ 1.51686175,  0.53725725]], shape=(6132, 2))

In [42]:
y_train

1444      33
1652     218
7496       0
1893     133
3880    1496
        ... 
5734    1507
5191     828
5390     999
860      322
7270    1501
Name: RentedBike, Length: 6132, dtype: int64

In [43]:
X_test

array([[-0.50562058,  1.19866927],
       [ 0.07223151,  1.65077368],
       [ 0.36115756,  1.76798594],
       ...,
       [ 1.2279357 , -0.02368712],
       [ 1.66132477, -1.16232047],
       [ 1.37239873, -0.73533296]], shape=(2628, 2))

In [44]:
y_test

6056    1728
5556     822
5990     658
7674    2716
3319    1083
        ... 
3404    1581
1912     404
3692    1401
599      169
45       377
Name: RentedBike, Length: 2628, dtype: int64

In [45]:
regl = linear_model.LinearRegression()

In [46]:
X_train = np.array(X_train)

In [47]:
regl.fit(X_train, y_train)


LinearRegression()

In [48]:
X_test = np.array(X_test)

In [49]:
pronostico = regl.predict(X_test)


In [50]:
pronostico

array([ 966.46804466, 1245.09360973, 1349.75026463, ...,  981.26110065,
        719.70669549,  788.33067873], shape=(2628,))

In [51]:
print('Coeficiente: ', regl.coef_)

Coeficiente:  [233.05157811 318.41366082]


In [52]:
print('Término independiente: ', regl.intercept_)

Término independiente:  702.6310506252892


In [53]:
print ('Error cuadrado medio: ', mean_squared_error(y_test, pronostico))

Error cuadrado medio:  244360.46419840018


In [56]:
valores_nuevos = np.array(X_train)  
pronostico_nuevos = regl.predict(valores_nuevos)
print(pronostico_nuevos)


[-189.22413501  490.74360191  545.26280117 ... 1229.78674592  554.72414522
 1227.20812204]
